version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Nicolas.73600
    ports:
      - "5432:5432"
    container_name: container-postgresdb
